### ISSUE TITLE
"error": "Method Illuminate\\Http\\Response::getBody does not exist."

### ISSUE THREAD

**Issue by swastik009** [schedula/laravel-passport-socialite#10]
There is an error on last line of issueToken method.

**Comment by anandsiddharth** [comment]
please paste the screenshot and a minimal code, so i can understand the issue

**Comment by swastik009** [comment]
return json_decode((string) $response->getBody(), true);
this is the line where the error happens, but if i write $response->content(); then it works

**Comment by anandsiddharth** [comment]
Got it, I have updated the doc. 
Thanks for reporting!
