### ISSUE TITLE
Laravel 6.x support

### ISSUE THREAD

**Issue by SanjuAppeonix** [schedula/laravel-passport-socialite#11]
> Using version ^2.0 for schedula/laravel-passport-socialite
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

>   Problem 1
    - Installation request for schedula/laravel-passport-socialite ^2.0 -> satisfiable by schedula/laravel-passport-socialite[v2.0.0].
    - Conclusion: remove laravel/framework v6.0.4
    - Conclusion: don't install laravel/framework v6.0.4
    - schedula/laravel-passport-socialite v2.0.0 requires illuminate/support ~5.7 -> satisfiable by illuminate/support[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.7.0, 
v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - don't install illuminate/support 5.7.17|don't install laravel/framework v6.0.4
    - don't install illuminate/support 5.7.18|don't install laravel/framework v6.0.4

and goes on.

**Comment by YoussF** [comment]
Hi,

What can i do to help make this issue fixed ? i really need this plugin to work with 6.x

Thank you.

**Comment by Fatima-yo** [comment]
I got the same issue today while trying to install schedula, any ideas?

**Comment by Fatima-yo** [comment]
This looks like a problem of incompatibility between versions, so if we would get to know what versions of Laravel and Illuminate we should use, it may go away.

**Comment by Paula2001** [comment]
guys I am getting this error - nexmo/client-core 1.8.1 requires php-http/guzzle6-adapter ^1.0 -> satisfiable by php-http/guzzle6-adapter[v1.0.0, v1.1.0, v1.1.1] but these conflict with your requirements or minimum-stability.

and this error 

- don't install illuminate/support 5.7.17|don't install laravel/framework v6.18.8
And I am using  "laravel/framework": "^6.2",

**Comment by DavidPrologo** [comment]
Hi guys. I had the same problem. The solution was run: "composer laravel/passport 9"; my laravel version = "6.20.16"
