### ISSUE TITLE
Versioning error

### ISSUE THREAD

**Issue by dpramani** [schedula/laravel-passport-socialite#3]
Hi Anand
 
I am developing a web app with socialite and passport. But while installing your package I am facing the following versioning error. Do you have any suggestion on that ? 

<img width="1167" alt="screen shot 2018-06-21 at 9 07 43 am" src="https://user-images.githubusercontent.com/26373096/41728137-47395e70-7533-11e8-9624-d186d71cffd5.png">

**Comment by anandsiddharth** [comment]
what is your laravel version

**Comment by dpramani** [comment]
Yes I am using 5.5.40. 
<img width="185" alt="screen shot 2018-06-21 at 12 31 39 pm" src="https://user-images.githubusercontent.com/26373096/41738348-137a150e-754f-11e8-9c6a-ecef35f60689.png">

**Comment by anandsiddharth** [comment]
can you paste the contents of composer.json here

**Comment by dpramani** [comment]
Yes sure.

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.0.0",
        "barryvdh/laravel-cors": "^0.11.0",
        "doctrine/dbal": "2.6.3",
        "fideloper/proxy": "~3.3",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "5.5.*",
        "laravel/passport": "~4.0",
        "laravel/socialite": "^3.0",
        "laravel/tinker": "~1.0",
        "league/oauth2-client": "^2.3",
        "predis/predis": "^1.1",
        "rollbar/rollbar-laravel": "^2.3",
        "socialiteproviders/google": "^3.0"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.4",
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~6.0",
        "roave/security-advisories": "dev-master"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
                "rollbar/rollbar-laravel"
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ],
        "post-update-cmd": [
            "php artisan ide-helper:generate",
            "php artisan ide-helper:meta",
            "php artisan ide-helper:models"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}

**Comment by anandsiddharth** [comment]
your laravel passport version is 4.0 supported version is 5.0 and 6.0 
check if you can upgrade 
we will be working on it further to support older version ,

Peace

**Comment by dpramani** [comment]
Thanks. I will try upgrading that.
