### ISSUE TITLE
Update to passport: ^7.0

### ISSUE THREAD

**Issue by stefensuhat** [schedula/laravel-passport-socialite#6]
`- schedula/laravel-passport-socialite v1.0.2 requires laravel/passport ^5.0 || ^6.0 -> satisfiable by laravel/passport[5.0.x-dev, 6.0.x-dev, v5.0.0, v5.0.1, v5.0.2, v5.0.3, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.0.5, v6.0.6, v6.0.7] but these conflict with your requirements or minimum-stability.`

**Comment by anandsiddharth** [comment]
https://github.com/schedula/laravel-passport-socialite/releases/tag/v1.0.3
