### ISSUE TITLE
Installation issue with laravel/socialite ^4.0

### ISSUE THREAD

**Issue by Trexology** [schedula/laravel-passport-socialite#8]
I have an issue when installing the package.

currently, I have socialite ^4.0 installed but this package requires laravel/socialite ^3.0

**Comment by anandsiddharth** [comment]
Drafted a new release try installing this major release 

The issue was caused due to this : https://github.com/laravel/socialite/blob/4.0/UPGRADE.md

https://github.com/anandsiddharth/laravel-paytm-wallet/releases/tag/v2.0.0

**Comment by anandsiddharth** [comment]
The above comment has updated correct link to the release!
